"""empty message

Revision ID: 5047e15006c3
Revises: 
Create Date: 2020-10-23 16:18:31.900350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5047e15006c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('notebook_name', sa.String(length=64), nullable=True),
    sa.Column('notebook_created_at_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('notebook_id')
    )
    op.create_index(op.f('ix_notebooks_notebook_created_at_date'), 'notebooks', ['notebook_created_at_date'], unique=False)
    op.create_index(op.f('ix_notebooks_notebook_name'), 'notebooks', ['notebook_name'], unique=True)
    op.create_table('chapters',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.Column('chapter_name', sa.String(length=120), nullable=True),
    sa.Column('chapter_created_at_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.notebook_id'], ),
    sa.PrimaryKeyConstraint('chapter_id')
    )
    op.create_index(op.f('ix_chapters_chapter_created_at_date'), 'chapters', ['chapter_created_at_date'], unique=False)
    op.create_table('notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.Column('note_name', sa.String(length=120), nullable=True),
    sa.Column('note_tags', sa.String(length=120), nullable=True),
    sa.Column('note_body', sa.Text(), nullable=True),
    sa.Column('note_created_at_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.notebook_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_notes_note_created_at_date'), 'notes', ['note_created_at_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_note_created_at_date'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_chapters_chapter_created_at_date'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_notebooks_notebook_name'), table_name='notebooks')
    op.drop_index(op.f('ix_notebooks_notebook_created_at_date'), table_name='notebooks')
    op.drop_table('notebooks')
    # ### end Alembic commands ###
